=head1 NAME

application - brief_description

=head1 SYNOPSIS

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 DESCRIPTION

=head1 DIAGNOSTICS

=head1 CONFIGURATION

=head1 DEPENDENCIES AND INCOMPATIBILITIES

=head1 BUGS AND LIMITATIONS

=head1 COPYRIGHT AND LICENSE

Copyright 2009 Vince Veselosky.

This program is distributed in the hope that it will be
useful, but without any warranty; without even the implied
warranty of merchantability or fitness for a particular purpose.

This program is free software; you
can redistribute it and/or modify it under the same terms
as Perl 5.10.0. For more details, see the full text of the
licenses in the directory LICENSES.

This program is free software; you can redistribute it and/or
modify it under the terms of either:

=over 4

=item * the GNU General Public License as published by the Free
Software Foundation; either version 2 <http://www.gnu.org/licenses/gpl-2.0.html>, 
or (at your option) any later version, or

=item * the Artistic License version 2.0 <http://www.perlfoundation.org/artistic_license_2_0>.

=back

